[package]
name = "iot-orchid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
paho-mqtt = "0.12"
rusqlite  = "0.29.0"
