version: '3'
services:
  api:
    image: ecrecords/iot-orchid:v0.1-alpha
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      IOT_ORCHID_PORT: ${IOT_ORCHID_PORT}
      IOT_ORCHID_ADDRESS: ${IOT_ORCHID_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mqtt

  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2.0.18
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  registration-handler:
    image: ecrecords/iot-orchid-registration:v0.1-alpha
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      IOT_ORCHID_PORT: ${IOT_ORCHID_PORT}
      IOT_ORCHID_ADDRESS: ${IOT_ORCHID_ADDRESS}
      JWT_SECRET: ${JWT_SECRET}
    build:
      context: .
      dockerfile: cmd/registration-handler/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db:
    driver: local

